### PR TITLE
add support for adding space-separated classes to `add-class` and `remove-class`

### LINKED ISSUE #52: addClass, hasClass, and removeClass will have issues with input containing whitespace characters
<sub>I'm including these three distinct issues in a single ticket as I believe that they should be resolved consistently.</sub>

[addClass][1], [hasClass][2], and [removeClass][3] will have inconsistent behavior between browsers when called with a class name such as `'foo bar'`.

## addClass

`addClass(el, 'foo bar')`

if the classList API is supported, a DOMException will be thrown
if the classList API is not supported `'foo bar'` will be added in a way that can cause class duplication.

## hasClass

`hasClass(el, 'foo bar')`

if the element happens to have those classes in that order, it will return `true`.

## removeClass

`removeClass(el, 'foo bar')`

if the classList API is supported, a DOMException will be thrown
if the classList API is not supported, `'foo bar'` will be removed only if those classes appear in that order.

# Recommendation

The API doesn't specify what should happen for trying to add multiple classes in a string. I believe that this should be fixed in a way to support utility to authors, even though it will cause a slight loss in performance and increase in code size.

I believe that it is obvious that `addClass(el, 'foo bar')` should be equivalent to `addClass(el, 'foo', 'bar')`, and that `removeClass(el, 'foo bar')` is equivalent to `removeClass(el, 'foo', 'bar')`.

I would also argue that `hasClass(el, 'foo bar')` should be treated as equivalent to `hasClass(el, 'foo') && hasClass(el, 'bar')`, however I am understanding of arguments for treating it as `hasClass(el, 'foo') || hasClass(el, 'bar')`, or explicitly disallowing that behavior to avoid possible author confusion.

That said, I am in favor of `hasClass(el, 'foo bar')` and the introduction of `hasClass(el, 'foo', 'bar')`, and `hasClass(el, ['foo', 'bar'])` as a means of specifying that an element has *all* of the listed classes.

[1]: https://github.com/AmpersandJS/amp/blob/master/modules/add-class/add-class.js
[2]: https://github.com/AmpersandJS/amp/blob/master/modules/has-class/has-class.js
[3]: https://github.com/AmpersandJS/amp/blob/master/modules/remove-class/remove-class.js

### PR DESCRIPTION
**Pull request by HenrikJoreteg**
Closes #52

### CODE REVIEW

**Comment by kamilogorek** [comment]
Nice! +1 :+1:

**Comment by fyockm** [comment]
LGTM :+1:

**Comment by latentflip** [comment]
+1

**Comment by HenrikJoreteg** [comment]
published as `1.1.0` of both

**Pull request merged**
