### PR TITLE
Add times.

### PR DESCRIPTION
**Pull request by mrDarcyMurphy**
Ports the underscore method to amp.

Also, the sizes for clone and merge were calculated a little differently than before after running `npm run build`. I'm not sure why, so I included those in a separate commit.

### CODE REVIEW

**Comment by HenrikJoreteg** [comment]
Hi @mrDarcyMurphy thanks for doing this! I know underscore categorizes this as a `utility`, but I'm not quite sure why it wouldn't go under `functions`. Anyone else have thoughts on that?

**Comment by mrDarcyMurphy** [comment]
@HenrikJoreteg To be honest, I originally threw it under `functions` without looking at where it was in underscore, then moved it under `utility` only after I looked it up. So putting it under `functions` is fine with me.

**Comment by wraithgar** [comment]
thanks @mrDarcyMurphy this will be merged in #81 (made a few small tweaks, keeping your commits though). Once it passes CI we can finish w/ the +1's, merge, and publish. thank you!

**Comment by mrDarcyMurphy** [comment]
Great. Thanks.

**Pull request closed without merging**
