### PR TITLE
add `invoke` method

### PR DESCRIPTION
**Pull request by HenrikJoreteg**
Should this tolerate missing methods? My thought is "no" because in that scenario you'd just use `map` and handle that exactly how you'd want to.

### CODE REVIEW

**Comment by bear** [comment]
is there any reason to not merge this?

**Comment by wraithgar** [comment]
This will have to be cleaned up to conform to the new modules.json format.

**Comment by HenrikJoreteg** [comment]
I almost did once :)  Yeah, just needs a few minor tweaks.

**Comment by HenrikJoreteg** [comment]
I think it's ready now.

**Comment by bear** [comment]
@wraithgar @kamilogorek can you "refresh" your prior +1's for this?

**Comment by wraithgar** [comment]
+1 good addition in re null/undefined

**Comment by jdalton** [comment]
> +1 good addition in re null/undefined

It's copied from Underscore edge. Surprise.

**Comment by HenrikJoreteg** [comment]
@jdalton this isn't helpful.

**Comment by jdalton** [comment]
> this isn't helpful.

Pointing to where code originated should be. The relevant fix was added [here](https://github.com/jashkenas/underscore/commit/644b35b1328d5bd633578378f4231a734f0bdf90) originating from [discussions in Underscore](https://github.com/jashkenas/underscore/pull/1994) which I was apart of.

**Comment by bear** [comment]
merging - thanks for the reviews!

**Comment by fyockm** [comment]
@jdalton making a snide remark - "Surprise" - is unnecessary. We've already established that much of amp comes from underscore. If you thought it useful to add background information to the issue (and I agree this was beneficial), it can be done without snark.

**Comment by jdalton** [comment]
Sorry for the hurt feels. I've redacted that bit :P

**Comment by jdalton** [comment]
> We've already established that much of amp comes from underscore.

My concern with copying edge is that it hasn't settled yet. Underscore has made changes in edge, reverted, or shifted direction many times in the past. In the case of `invoke` their implementation is still [being refined](https://github.com/jashkenas/underscore/issues/2000) so amp is missing out. I think it more makes sense if amp is set on copying Underscore to wait until the given API is at least in a tagged release.

**Comment by govpack** [comment]
Does valentine's day have two "l's" or one? Is it like commentary from some source material not totally applying to the current project? So it's confusable because the comment applies to something other than what this is? +1 to painting the house blue, whereas this isn't a house it's a boot. Hence the surprise -- ie figuring that out -- unless it's obviously snarky, or even if it is, it's snarky, to say that it's snarky, and that's only someone's label anyway, and a negative one at that. Almost everything everyone says is "unnecessary" but who want's to be the one to judge or censor that? Too many words. Freedom and self expression should mostly go un-judged. Just worry about your own communication and let other people worry about theirs.

**Pull request merged**
