### PR TITLE
Add union and intersection.

### LINKED ISSUE #75: add `union` we need it for `ampersand-state`
as mentioned in https://github.com/AmpersandJS/ampersand-state/pull/131

### PR DESCRIPTION
**Pull request by latentflip**
Basically just a straight port from underscore. Required for AmpersandJS/ampersand-state#131

Closes #75

### CODE REVIEW

**Comment by wraithgar** [comment]
:+1:

**Comment by fyockm** [comment]
Interesting to me that `intersection` has a couple tests around `null`, and `union` has tests for nested arrays - but not vice versa. Might be nice to add those. Otherwise LGTM.

**Comment by latentflip** [comment]
@fyockm that was just straight from underscore tests. Will add some more.

**Comment by HenrikJoreteg** [comment]
@wraithgar suggested we can add additional tests post 1.0.0 on this, given that it's a straight port from underscore.

**Comment by HenrikJoreteg** [comment]
+1 from me, will ship once CI passes.

**Comment by HenrikJoreteg** [comment]
published.

**Pull request merged**
