### PR TITLE
Compact

### PR DESCRIPTION
**Pull request by HenrikJoreteg**
Includes commits from #77

### CODE REVIEW

**Comment by HenrikJoreteg** [comment]
This one is basic enough, i'm just going push the trigger.

**Comment by HenrikJoreteg** [comment]
published as `1.0.0` thanks @brianberlin

**Comment by HenrikJoreteg** [comment]
http://amp.ampersandjs.com/#amp-compact

**Comment by brianberlin** [comment]
awesome! thanks @HenrikJoreteg

**Pull request merged**
