### PR TITLE
add sorted-push and sorted-index

### PR DESCRIPTION
**Pull request by wraithgar**
This allows you to push items into an already sorted array and maintain the sort order without having to manually resort the whole array.

### CODE REVIEW

**Comment by wraithgar** [comment]
I have no idea what this function should actually be called. The three ways I know of to get values into an array are push, unshift, and splice. This technically splices under the hook but when I wrote it it was replacing a `push()` then `.sort()` chain.

**Comment by wraithgar** [comment]
Looks like this functionality should be ported instead? http://underscorejs.org/#sortedIndex

You'll notice `sortedIndexOf` is just a function inside of this new module but it could totally be separated out, and maybe should be?

**Comment by HenrikJoreteg** [comment]
In thinking about this, I don't think we should call it `sorted-push` because "push" implies pushing it onto a stack. What do you think about `sorted-insert`?

**Comment by fyockm** [comment]
I definitely like `sorted-insert` better than `sorted-push` for the reason @HenrikJoreteg stated.

My other suggestion would be `sorted-add`, similar to http://ampersandjs.com/docs/#ampersand-collection-add

**Comment by HenrikJoreteg** [comment]
I think "insert" implies position more strongly than "add".

**Comment by wraithgar** [comment]
Ok renamed to sorted-insert, and also made it actually use sorted-index which I somehow forgot to check in before.

**Comment by HenrikJoreteg** [comment]
I think this is ready for merge and initial publish. @AmpersandJS/core-team feedback appreciated.

**Comment by HenrikJoreteg** [comment]
inserting in-person +1 i just got from @wraithgar :)

**Comment by fyockm** [comment]
:shipit:

**Comment by HenrikJoreteg** [comment]
woot! shipped.

**Pull request merged**
