### PR TITLE
adding array-to-readable

### PR DESCRIPTION
**Pull request by HenrikJoreteg**

### CODE REVIEW

**Comment by wraithgar** [comment]
Couldn't this be `amp-array-join` if you made the separator also configurable (defaulting to `,` still)?

**Comment by HenrikJoreteg** [comment]
@wraithgar only thing is, the fact that it joins the stuff isn't what's useful, IMO. It's the fact that it's producing a human friendly string. What else would you use it for?

**Comment by bear** [comment]
Could you use amp-array-join with the default of "," and a flag for human readable?

In the python world .join() is used for this case (as an example)

**Comment by HenrikJoreteg** [comment]
@bear while i could, there's really not much reason to do so. Given that `Array.prototype.join` [exists and does exactly that](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join). If that's all you want, you wouldn't use this module.

**Comment by wraithgar** [comment]
+1 my question was answered

**Pull request merged**
