### PR TITLE
release/to-kebab-case

### PR DESCRIPTION
**Pull request by cdaringe**
Hi all:

Sometimes, a guy/girl just needs a kebab.

Doner Kebab
Non-traditional, but doner kebabs (kebaps?) are the best!

I tested everything in sauce and local--they all checked out.  However, just prior to PR, my `npm test` fails no matter what, even if all tests are passing (note: it was working prior even with all of my changes in).  I think it's an issue just to my local machine, but FYI, I bypassed the precommit hook :(.  Still looking into whats going on w/ my npm.

Let me know if i left anything out!  Thanks.

### CODE REVIEW

**Comment by cdaringe** [comment]
1) By the way, the implementation is my own, so if anyone has perf improvements or input, I'm all ears.  Thanks!
2) this is failing on invalid sauce credentials?  i saw how to do this for my machine, but not for the build server.  it's way past bedtime.  tips there would be appreciated

**Comment by cdaringe** [comment]
@bear, do you know how I can get the saucelabs credentials going for the build?

**Comment by bear** [comment]
@cdaringe i'll get you the encrypted entry later today

**Comment by bear** [comment]
@cdaringe I updated the sauce labs section of travis

**Comment by cdaringe** [comment]
Thanks @bear!  Would you be willing to restart the build?  I don't have access.  I could push another commit if reqd.

**Comment by bear** [comment]
I have had mixed luck with master branch travis-ci changes and then PR tests - can you push a commit?

**Comment by cdaringe** [comment]
@bear, looks like the credentials are still failing.  No rush.  We can try again whenever.

**Comment by bear** [comment]
i'll swing by after a bit - thanks!

**Comment by cdaringe** [comment]
@bear, it's still failing on credentials.  Perhaps you're missing the equivalent of?:

```yml
env:
  global:
  - secure: "asdfadsfkjaklsaiosdfasd37BNp4="
  - secure: "asdfafawefwefewoqpoputYs="
```

per the [travis docs](https://docs.saucelabs.com/ci-integrations/travis-ci/#adding-credentials-for-a-public-github-repo)

**Comment by wraithgar** [comment]
Since this never shipped and we point people to lodash on methods that overlap anyways I'm gonna close this

**Comment by cdaringe** [comment]
#kebabs4lyfe

**Pull request closed without merging**
