### PR TITLE
Added `next`, `pick`, `negate`, `omit`

### PR DESCRIPTION
**Pull request by jvduf**
I've merged my previous PR's into a single clean one as the previous ones became a mess because I did not use different branches. Hereby clean without any conflicts/merges etc my contributions :)

### CODE REVIEW

**Comment by jvduf** [comment]
@bear still the Travis issue which fails the tests :(

`Zuul tried to run tests in saucelabs, however no saucelabs credentials were provided.`

**Comment by bear** [comment]
yea, i'm fighting one of my own tools - it adds the TravisCI hook back. I've got a bug report against myself to add in a per repo exclude list

**Comment by jvduf** [comment]
@wraithgar @HenrikJoreteg @bear, care to review and +1? Would love to start porting `underscore` to `amp` in certain modules and use these updates.

**Comment by wraithgar** [comment]
+1 looks good, tests pass

**Comment by kamilogorek** [comment]
Same here, looks fine.

**Comment by bear** [comment]
Thanks for the reviews and thanks @jvduf for the work - merging!

**Comment by jvduf** [comment]
awesome! thanks all.

**Comment by HenrikJoreteg** [comment]
There are some tweaks I think we should make before publishing these, sorry. 

First, I think we should use: https://github.com/HenrikJoreteg/array-jumper/blob/master/array-jumper.js instead of https://github.com/HenrikJoreteg/array-next/blob/master/array-next.js as the array next-implementation. Possibly calling it array-jump instead.

**Comment by HenrikJoreteg** [comment]
Also the docs and tests on that should cover what happens in some of the edge-cases. I feel like that one  wasn't ready quite yet.

**Comment by jvduf** [comment]
So do your comments apply to `next` specifically or the other modules as well?

**Comment by HenrikJoreteg** [comment]
I think that's it. Curious on your thoughts on `next` though.

**Comment by HenrikJoreteg** [comment]
We should also cache references to prototype methods instead of accessing them directly like this: https://github.com/AmpersandJS/amp/blob/master/modules/pick/pick.js#L15.

This is also different than the underscore implementation which uses `flatten` here. We should look into why.

**Comment by jvduf** [comment]
@HenrikJoreteg 

re: `flatten`, that changed only two days ago... I missed this commit.

re: `array-jumper` looks good to me as well, so replace the `array-next` in the `ampersand` modules with this?

**Comment by HenrikJoreteg** [comment]
I discussed this with @jvduf in chat, we're both pro doing an `array-jump` instead of `array-next`. PR incoming on that.

**Pull request merged**
